# Generated by Django 5.2.7 on 2025-10-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='events_rsvp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='events.event'),
        ),
    ]
