# Generated by Django 5.2.7 on 2025-10-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
