# Generated by Django 5.2.7 on 2025-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default_img.jpg', null=True, upload_to='events_asset'),
        ),
    ]
