# Generated by Django 5.2.7 on 2025-10-05 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_rsvp_event_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rsvp',
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='events_rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
